(exit_code) Fix ident

diff --git a/install/install-pulse b/install/install-pulse
--- a/install/install-pulse
+++ b/install/install-pulse
@@ -222,8 +222,8 @@ sed_escape() {
 }
 
 exit_code() {
-  return=$?
-  if [ $return -ne 0 ];then coloredEcho red "### DEBUG Exit code" $return; fi
+    return=$?
+    if [ $return -ne 0 ];then coloredEcho red "### DEBUG Exit code" $return; fi
 }
 
 
