Merge all changes to install-pulse from xmppmaster to master except those concerning syncthing

diff --git a/install/install-pulse b/install/install-pulse
--- a/install/install-pulse
+++ b/install/install-pulse
@@ -499,6 +499,13 @@ configure_repos() {
 
 	wget -qO - ${PULSE_REPO_URL}/pubkey.txt | apt-key add -
 
+    if [ $? -eq 2 ]; then
+        echo "We failed to import the pubkey"
+        echo "You may need to check that http_proxy and https_proxy variables are correctly exported"
+        exit 1
+    fi
+
+
 	apt -y install apt-transport-https
 
 	case ${DEBIAN_VERSION} in
@@ -519,7 +526,11 @@ configure_repos() {
                                         echo "deb ${PULSE_REPO_URL} xmppmaster mmc-core pulse 3rdparty" > /etc/apt/sources.list.d/pulse.list
                                 fi
                         else
-                                echo "deb ${PULSE_REPO_URL} stretch mmc-core pulse 3rdparty" > /etc/apt/sources.list.d/pulse.list
+                                if [ ! -z ${GIT_BRANCH} ] && [ ${GIT_BRANCH} != "master" ]; then
+                                        echo "deb ${PULSE_REPO_URL} ${GIT_BRANCH} mmc-core pulse 3rdparty" > /etc/apt/sources.list.d/pulse.list
+                                else
+                                        echo "deb ${PULSE_REPO_URL} stretch mmc-core pulse 3rdparty" > /etc/apt/sources.list.d/pulse.list
+                                fi
                         fi
 
 			;;
@@ -1292,6 +1303,9 @@ configure_guacamole() {
 	# Setup Apache
 	echo "<Location /guacamole/>" > /etc/apache2/conf-available/guacamole.conf
   echo "    SetEnvIf Referer \"^https?://${SERVER_FQDN}/\" GUACAMOLE_ALLOWED" >> /etc/apache2/conf-available/guacamole.conf
+  if [[ -v PULSEMAIN_IP ]]; then
+      echo "    SetEnvIf Referer \"^https?://${PULSEMAIN_IP}/\" GUACAMOLE_ALLOWED" >> /etc/apache2/conf-available/guacamole.conf
+  fi
   echo "    Order Deny,Allow" >> /etc/apache2/conf-available/guacamole.conf
   echo "    Deny from all" >> /etc/apache2/conf-available/guacamole.conf
   echo "    Allow from env=GUACAMOLE_ALLOWED" >> /etc/apache2/conf-available/guacamole.conf
@@ -1300,6 +1314,9 @@ configure_guacamole() {
   echo "</Location>" >> /etc/apache2/conf-available/guacamole.conf
   echo "<Location /guacamole/websocket-tunnel>" >> /etc/apache2/conf-available/guacamole.conf
   echo "    SetEnvIf Referer \"^https?://${SERVER_FQDN}/\" GUACAMOLE_ALLOWED" >> /etc/apache2/conf-available/guacamole.conf
+  if [[ -v PULSEMAIN_IP ]]; then
+      echo "    SetEnvIf Referer \"^https?://${PULSEMAIN_IP}/\" GUACAMOLE_ALLOWED" >> /etc/apache2/conf-available/guacamole.conf
+  fi
   echo "    Order Deny,Allow" >> /etc/apache2/conf-available/guacamole.conf
   echo "    Deny from all" >> /etc/apache2/conf-available/guacamole.conf
   echo "    Allow from env=GUACAMOLE_ALLOWED" >> /etc/apache2/conf-available/guacamole.conf
@@ -1393,7 +1410,10 @@ reset_glpi_db() {
 	dpkg-reconfigure -fnoninteractive glpi
 
 	# Upgrade database if needed
-	php /usr/share/glpi/tools/cliupdate.php
+	php /usr/share/glpi/scripts/cliupdate.php
+
+    # Create the view for glpi 9.2
+    mysql -uroot < /usr/share/doc/pulse2/contrib/glpi-92.sql
 
 	# Clean glpi users/profiles apart from glpi superadmin
 	local GLPI_SUPERADMIN_ID=`echo "select name,id from glpi_users;" | mysql -uroot glpi --silent | grep "^glpi[[:space:]]\+" | awk -F'\t' '{ print $2 }'`
@@ -1431,6 +1451,7 @@ reset_glpi_db() {
         (${SuperAdmin},'plugin_fusioninventory_deploymirror',23), \
         (${SuperAdmin},'plugin_fusioninventory_esx',23), \
         (${SuperAdmin},'plugin_fusioninventory_group',23), \
+        (${SuperAdmin},'plugin_fusioninventory_ignoredimportdevice',23), \
         (${SuperAdmin},'plugin_fusioninventory_importxml',4), \
         (${SuperAdmin},'plugin_fusioninventory_iprange',23), \
         (${SuperAdmin},'plugin_fusioninventory_lock',23), \
@@ -1445,8 +1466,10 @@ reset_glpi_db() {
         (${SuperAdmin},'plugin_fusioninventory_ruleentity',23), \
         (${SuperAdmin},'plugin_fusioninventory_ruleimport',23), \
         (${SuperAdmin},'plugin_fusioninventory_rulelocation',23), \
+        (${SuperAdmin},'plugin_fusioninventory_selfpackage',1), \
         (${SuperAdmin},'plugin_fusioninventory_task',23), \
         (${SuperAdmin},'plugin_fusioninventory_unmanaged',31), \
+        (${SuperAdmin},'plugin_fusioninventory_userinteractiontemplate',23), \
         (${SuperAdmin},'plugin_fusioninventory_wol',1)" | mysql glpi
   php /usr/share/glpi/plugins/fusioninventory/scripts/cli_install.php
   echo "update glpi_plugin_fusioninventory_entities SET  agent_base_url = 'http://127.0.0.1/glpi' , transfers_id_auto = '1'  WHERE id='1';" | mysql glpi
@@ -1706,6 +1729,22 @@ configure_relay_server() {
 	systemctl enable pulse-xmpp-agent-relay.service
 	service pulse-xmpp-agent-relay start
 
+    # Create the clusters of ARS for multisite installs
+    if [[ ${XMPP_DOMAIN} != 'pulse' ]]; then
+        # First wait a few minutes until the relay server is configured
+        sleep 2m
+        # Create the cluster for the remote site
+        local MAX_ID=$(ssh ${PULSEMAIN_IP} "echo 'SELECT MAX(id) FROM cluster_ars;' | mysql -s xmppmaster")
+        local CLUSTER_ID=$((MAX_ID+1))
+        local SSH_COMMAND="echo \"INSERT INTO cluster_ars (id,name,description) VALUES (${CLUSTER_ID},'${MULTISITE_ENTITY// /_}','${MULTISITE_ENTITY}');\" | mysql xmppmaster"
+    	ssh ${PULSEMAIN_IP} ${SSH_COMMAND}
+        # Add the relayserver to the cluster
+        local MAX_ID=$(ssh ${PULSEMAIN_IP} "echo 'SELECT MAX(id) FROM has_cluster_ars;' | mysql -s xmppmaster")
+        local RELAYSERVER_ID=$(ssh ${PULSEMAIN_IP} "echo \"SELECT id FROM relayserver WHERE nameserver='${XMPP_DOMAIN}';\" | mysql -s xmppmaster")
+        local SSH_COMMAND="echo \"INSERT INTO has_cluster_ars (id,id_ars,id_cluster) VALUES ('$((MAX_ID+1))','${RELAYSERVER_ID}','${CLUSTER_ID}');\" | mysql xmppmaster"
+        ssh ${PULSEMAIN_IP} ${SSH_COMMAND}
+    fi
+
 	colored_echo green "### INFO Configuring relay server... Done"
 }
 
@@ -1726,13 +1765,13 @@ install_multisite_dependencies() {
 	install_pxelinux
 	install_clonezilla
 	install_samba
-	install_xmpp_server ${MULTISITE_ENTITY}
+	install_xmpp_server $(hostname)
 	install_guacamole_server
 }
 
 install_multisite() {
 	colored_echo blue "### INFO Installing Pulse multisite..."
-	apt -y install pulse2-package-server uuid-runtime pulse2-uuid-resolver pulse-xmpp-agent pulseagent-plugins-relay
+	apt -y install pulse2-package-server uuid-runtime pulse2-uuid-resolver pulse-xmpp-agent pulseagent-plugins-relay python-mmc-backuppc
 	if [ ! $? -eq 0 ]; then
 		colored_echo red "### ERROR... Pulse install... failed"
 		exit 1
@@ -1747,7 +1786,7 @@ configure_multisite_dependencies() {
 	configure_pxelinux
 	configure_clonezilla
 	configure_samba
-	configure_xmpp_server ${MULTISITE_ENTITY}
+	configure_xmpp_server $(hostname)
 	configure_guacamole
 }
 
@@ -1876,7 +1915,7 @@ configure_multisite() {
 
 	configure_package_server_multisite
 	create_package_server_cert
-	configure_relay_server ${MULTISITE_ENTITY}
+	configure_relay_server $(hostname)
 
 	colored_echo blue "### INFO Restart pulse2-package-server..."
 	systemctl restart pulse2-package-server.service
