(install_glpi) Fix ident

diff --git a/install/install-pulse b/install/install-pulse
--- a/install/install-pulse
+++ b/install/install-pulse
@@ -1026,29 +1026,29 @@ initialise_glpi_db() {
 }
 
 install_glpi() {
-        colored_echo blue "### INFO Installing GLPI..."
+    colored_echo blue "### INFO Installing GLPI..."
 
-        if [[ $LINUX_DISTRO == "debian" ]]; then
-        # Define a few settings for glpi
-                echo "glpi glpi/password-confirm password ${ROOT_PASSWORD}" | debconf-set-selections
-                echo "glpi glpi/mysql/app-pass password ${ROOT_PASSWORD}" | debconf-set-selections
-                echo "glpi glpi/mysql/admin-pass password ${ROOT_PASSWORD}" | debconf-set-selections
-                echo "glpi glpi/purge boolean false" | debconf-set-selections
-                echo "glpi glpi/db/dbname string glpi" | debconf-set-selections
-                echo "glpi glpi/dbconfig-reinstall boolean false" | debconf-set-selections
-                echo "glpi glpi/db/app-user string glpi" | debconf-set-selections
-                echo "glpi glpi/dbconfig-install boolean true" | debconf-set-selections
-                echo "glpi glpi/webserver multiselect apache, apache-ssl, apache-perl, apache2" | debconf-set-selections
-                echo "glpi glpi/configuration note" | debconf-set-selections
-        else
-                initialise_glpi_db
-        fi
-        # Install glpi
-        apt -y install glpi fusioninventory-for-glpi
-        if [ ! $? -eq 0 ]; then
-                colored_echo red "### ERROR... GLPI install... failed"
-                exit 1
-        fi
+    if [[ $LINUX_DISTRO == "debian" ]]; then
+    # Define a few settings for glpi
+        echo "glpi glpi/password-confirm password ${ROOT_PASSWORD}" | debconf-set-selections
+        echo "glpi glpi/mysql/app-pass password ${ROOT_PASSWORD}" | debconf-set-selections
+        echo "glpi glpi/mysql/admin-pass password ${ROOT_PASSWORD}" | debconf-set-selections
+        echo "glpi glpi/purge boolean false" | debconf-set-selections
+        echo "glpi glpi/db/dbname string glpi" | debconf-set-selections
+        echo "glpi glpi/dbconfig-reinstall boolean false" | debconf-set-selections
+        echo "glpi glpi/db/app-user string glpi" | debconf-set-selections
+        echo "glpi glpi/dbconfig-install boolean true" | debconf-set-selections
+        echo "glpi glpi/webserver multiselect apache, apache-ssl, apache-perl, apache2" | debconf-set-selections
+        echo "glpi glpi/configuration note" | debconf-set-selections
+    else
+        initialise_glpi_db
+    fi
+    # Install glpi
+    apt -y install glpi fusioninventory-for-glpi
+    if [ ! $? -eq 0 ]; then
+        colored_echo red "### ERROR... GLPI install... failed"
+        exit 1
+    fi
 
         colored_echo green "### INFO Installing GLPI... Done"
 }
